# Generated by Django 5.0.6 on 2024-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0002_routesaledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_identification_number', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=20)),
                ('roc', models.CharField(max_length=50)),
                ('company_category', models.CharField(max_length=50)),
                ('company_subcategory', models.CharField(max_length=50)),
                ('class_of_company', models.CharField(max_length=50)),
                ('date_of_incorporation', models.CharField(max_length=50)),
                ('age_of_company', models.CharField(max_length=50)),
                ('total_members', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('phone_number_1', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id_1', models.EmailField(max_length=254)),
                ('email_id_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gstin', models.CharField(max_length=15)),
                ('company_activity', models.TextField()),
            ],
        ),
    ]
