# Generated by Django 5.0.6 on 2024-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0004_directordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='directordetails',
            name='signature',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
