# Generated by Django 5.0.6 on 2024-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0006_shareholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(max_length=10, null=True)),
                ('license_number', models.CharField(max_length=50, null=True)),
                ('expiry_remainder', models.CharField(max_length=50, null=True)),
                ('expiry_date', models.CharField(max_length=10, null=True)),
                ('licenseFile', models.ImageField(blank=True, null=True, upload_to='licenses/')),
            ],
        ),
    ]
