# Generated by Django 5.0.6 on 2024-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0008_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=255)),
                ('stateandtin', models.EmailField(max_length=255)),
                ('gst', models.CharField(max_length=50, null=True)),
                ('taxtype', models.EmailField(max_length=255)),
            ],
        ),
    ]
