# Generated by Django 5.0.6 on 2024-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0009_vendordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='taxmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('goods_service', models.CharField(max_length=10, null=True)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('compensation_cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flood_cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
