# Generated by Django 5.0.6 on 2024-06-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0011_purchasedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='supplier_name',
            new_name='MOP',
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='CGST',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='CGST_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='IGST',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='IGST_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='Mrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='Prate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='QTY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='SGST',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='SGST_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='TAX_MODE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='bill_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='discount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='gross_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='purchase_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='purchase_tax',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='reciept_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='referal_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='taxable_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.vendordetails'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='invoice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='item_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='totalprice',
            field=models.BigIntegerField(null=True),
        ),
    ]
