# Generated by Django 5.0.6 on 2024-06-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0012_rename_supplier_name_purchasedetails_mop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_PHOTO', models.ImageField(blank=True, null=True, upload_to='memberphoto/')),
                ('Member_TYPE', models.CharField(max_length=50, null=True)),
                ('Member_ID', models.CharField(max_length=50, null=True)),
                ('Member_NAME', models.CharField(max_length=50, null=True)),
                ('Member_ADDRESS', models.CharField(max_length=50, null=True)),
                ('Member_PHONE_NNUMBER', models.CharField(max_length=255)),
                ('Member_EMAIL', models.EmailField(max_length=255)),
                ('Member_ADHAR_NO', models.CharField(max_length=50, null=True)),
                ('Member_GST', models.CharField(max_length=50, null=True)),
                ('Member_DATE_OF_JOINING', models.CharField(max_length=10, null=True)),
                ('Member_OPENING_BALENCE', models.CharField(max_length=50, null=True)),
                ('Member_CURRENT_BALANCE', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseDetails',
        ),
    ]
