# Generated by Django 5.0.6 on 2024-06-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0013_member_delete_purchasedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField(null=True)),
                ('purchase_date', models.CharField(max_length=10, null=True)),
                ('item_count', models.IntegerField(null=True)),
                ('totalprice', models.BigIntegerField(null=True)),
                ('bill_number', models.BigIntegerField(null=True)),
                ('referal_number', models.BigIntegerField(null=True)),
                ('reciept_date', models.CharField(max_length=10, null=True)),
                ('MOP', models.CharField(max_length=100, null=True)),
                ('TAX_MODE', models.CharField(max_length=100, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('QTY', models.IntegerField(null=True)),
                ('unit', models.IntegerField(null=True)),
                ('Prate', models.IntegerField(null=True)),
                ('Mrp', models.IntegerField(null=True)),
                ('discount', models.BigIntegerField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('taxable_amount', models.BigIntegerField(null=True)),
                ('CGST', models.BigIntegerField(null=True)),
                ('CGST_amount', models.BigIntegerField(null=True)),
                ('SGST', models.BigIntegerField(null=True)),
                ('SGST_amount', models.BigIntegerField(null=True)),
                ('IGST', models.BigIntegerField(null=True)),
                ('IGST_amount', models.BigIntegerField(null=True)),
                ('gross_amount', models.BigIntegerField(null=True)),
                ('purchase_tax', models.BigIntegerField(null=True)),
                ('purchase_amount', models.BigIntegerField(null=True)),
                ('x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.vendordetails')),
            ],
        ),
    ]
