# Generated by Django 5.0.6 on 2024-06-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0015_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='x',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='CGST',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='CGST_amount',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='IGST',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='IGST_amount',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='MOP',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='Mrp',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='Prate',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='QTY',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='SGST',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='SGST_amount',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='TAX_MODE',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='referal_number',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vendordetails',
            name='stateandtin',
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='bill_no',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='net_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='net_total',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='new_balance',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='old_balalnce',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='paid_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.products'),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='qty_total',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='ref_no',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='total_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='state',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='state_type',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='discount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='gross_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='purchase_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='purchase_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='purchase_tax',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='reciept_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='taxable_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='address',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='e_mail',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='taxtype',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='cgst_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='igst',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='igst_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='mop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='prate',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='qty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='sgst',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='sgst_amount',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='tax_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
