# Generated by Django 5.0.6 on 2024-06-20 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0018_remove_purchasedetails_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='hsn_code',
        ),
        migrations.AlterField(
            model_name='products',
            name='hsn_code_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.taxmaster'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.productcategory'),
        ),
    ]
