# Generated by Django 5.0.6 on 2024-06-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0019_remove_products_hsn_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='sgst',
        ),
    ]
