# Generated by Django 5.0.6 on 2024-06-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0020_remove_purchased_products_cgst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='net_total',
            new_name='taxable_amount',
        ),
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='purchase_amount',
            new_name='total_discount',
        ),
    ]
