# Generated by Django 5.0.6 on 2024-06-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0021_rename_net_total_purchasedetails_taxable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_products',
            name='MRP',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='cgst_amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='discount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='igst_amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='net_amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='prate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='sgst_amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='taxable_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
