# Generated by Django 5.0.6 on 2024-06-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0022_alter_purchased_products_mrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damaged_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damaged_qty', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('current_stock', models.CharField(max_length=50, null=True)),
                ('stock_balance', models.CharField(max_length=50, null=True)),
                ('prod_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.products')),
            ],
        ),
    ]
