# Generated by Django 5.0.6 on 2024-07-06 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('venadApp', '0024_damaged_products_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.PositiveIntegerField()),
                ('mop', models.CharField(max_length=10)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shareholder_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgstamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgstamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igstamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('netamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.products')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.sale')),
            ],
        ),
    ]
