# Generated by Django 5.0.6 on 2024-07-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0025_sale_saleproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_qty', models.CharField(max_length=35, null=True)),
                ('ret_amt', models.CharField(max_length=250, null=True)),
                ('ret_date', models.DateField(max_length=50, null=True)),
                ('pur_det', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.purchased_products')),
            ],
        ),
    ]
