# Generated by Django 5.0.6 on 2024-07-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0026_purchasereturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='pur_det',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='ret_amt',
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='pur_ret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.purchasereturn'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='ret_qty',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
