# Generated by Django 5.0.6 on 2024-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0027_remove_purchasereturn_pur_det_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='ret_amt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='ret_qty',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
