# Generated by Django 5.0.6 on 2024-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0028_purchasereturn_ret_amt_alter_purchasereturn_ret_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='ret_qty',
            field=models.CharField(default='0', max_length=35, null=True),
        ),
    ]
