# Generated by Django 5.0.6 on 2024-07-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venadApp', '0029_alter_purchasereturn_ret_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='pur_ret',
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='pur_ret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venadApp.purchased_products'),
        ),
    ]
